(module queues ()
  (import scheme)
  (import (only chicken include define-record-type case-lambda error))
  (export make-queue queue queue-copy queue-unfold queue-unfold-right)
  (export queue? queue-empty?)
  (export queue-front queue-back)
  (export queue-add-front! queue-add-back! queue-remove-front! queue-remove-back!)
  (export queue-remove-all!)
  (export queue-clear!)
  (export queue-length queue-append queue-concatenate)
  (export queue-map queue-map! queue-for-each)
  (export queue-list make-queue-with-list queue-set-list!)
  (export queue-first-last make-queue-with-first-last queue-set-first-last!)
  (include "queues-impl.scm")
)
