;;;; genequal.import.scm - GENERATED BY CHICKEN 4.8.2 -*- Scheme -*-

(eval '(import scheme chicken srfi-4))
(##sys#register-compiled-module
  'genequal
  (list)
  '((generalized-equal? . genequal#generalized-equal?)
    (make-atomic-comparator . genequal#make-atomic-comparator)
    (make-specific-equality . genequal#make-specific-equality)
    (numeric-comparator . genequal#numeric-comparator)
    (char-ci-comparator . genequal#char-ci-comparator)
    (list-comparator . genequal#list-comparator)
    (string-comparator . genequal#string-comparator)
    (string-ci-comparator . genequal#string-ci-comparator)
    (vector-comparator . genequal#vector-comparator)
    (bytevector-comparator . genequal#bytevector-comparator))
  (list)
  (list))

;; END OF FILE
